server:
  port: 8888

spring:
  application:
    name: hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    # 表示是否从Eureka Server获取注册信息
    fetch-registry: true
  instance:
    #标识eureka client 给服务端发送信息的频率 10s
    lease-renewal-interval-in-seconds: 10
    #eureka server 在30s 后，没有收到 client信息的心跳,则将注册的客户端移除
    lease-expiration-duration-in-seconds: 30
    # 配置使用主机名注册服务
    hostname: localhost
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

#@FeignClient 全局Fallback开启,断熔处理
feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework: warn
#  file:
#    path: logs/hello/
#    max-size: 100MB