server:
  port: 8001

spring:
  application:
    name: service-eureka-server

eureka:
  instance:
    hostname: localhost

  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #清理无效节点 4s
    eviction-interval-timer-in-ms: 4000

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    org.springframework: warn
    com.netflix.eureka.registry.AbstractInstanceRegistry: warn
  pattern:
    level:
    file:
    console: '%clr(%d{YYYY:HH:mm:ss}){yellow} %-5level %clr(%logger){green}  %msg%n'
